builds:
  - binary: '{{ .ProjectName }}_v{{ .Version }}'
    env:
      - CGO_ENABLED=0
    goarch:
      - arm64
      - amd64
    goos:
      - darwin
      - linux
archives:
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
#signs:
#  - artifacts: checksum
#    args:
#      - "--batch"
#      - "--local-user"
#      - "{{ .Env.GPG_FINGERPRINT }}" # set this environment variable for your signing key
#      - "--output"
#      - "${signature}"
#      - "--detach-sign"
#      - "${artifact}"
release:
  github:
    owner: "petetanton"
    name: "reclaim-cli"
  draft: false
changelog:
  disable: true