on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: go mod
        run: go mod tidy
      - name: commit docs
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update go mod
          file_pattern: 'go.*'
      - name: Build
        run: go build main.go