on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: generate version
        run: |
          echo "package version" > pkg/version/version.go
          echo "" >> pkg/version/version.go
          echo "const Version = \"${{ github.ref_name }}\"" >> pkg/version/version.go
      - name: commit version
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update version.go
          file_pattern: 'pkg/version.go'
      - name: go mod
        run: go mod tidy
      - name: commit mod and sum
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update go mod
          file_pattern: 'go.*'
      - name: Build
        run: go build main.go